country = Spree::Country.find_or_create_by_name(name: "Brazil", iso3: "BRA", iso: "BR", iso_name: "BRAZIL", numcode: "76", states_required: true)

Spree::State.create!([
	{name:'Amazonas', abbr:'AM', country: country},
	{name:'Pará', abbr:'PA', country: country},
	{name:'Mato Grosso', abbr:'MT', country: country},
	{name:'Minas Gerais', abbr:'MG', country: country},
	{name:'Bahía', abbr:'BA', country: country},
	{name:'Mato Grosso do Sul', abbr:'MS', country: country},
	{name:'Goiás', abbr:'GO', country: country},
	{name:'Maranhão', abbr:'MA', country: country},
	{name:'Tocantins', abbr:'TO', country: country},
	{name:'Rio Grande do Sul', abbr:'RS', country: country},
	{name:'Piauí', abbr:'PI', country: country},
	{name:'São Paulo', abbr:'SP', country: country},
	{name:'Rondonia', abbr:'RO', country: country},
	{name:'Roraima', abbr:'RR', country: country},
	{name:'Paraná', abbr:'PR', country: country},
	{name:'Acre', abbr:'AC', country: country},
	{name:'Ceará', abbr:'CE', country: country},
	{name:'Amapá', abbr:'AP', country: country},
	{name:'Pernambuco', abbr:'PE', country: country},
	{name:'Santa Catarina', abbr:'SC', country: country},
	{name:'Paraíba', abbr:'PB', country: country},
	{name:'Rio Grande do Norte', abbr:'RN', country: country},
	{name:'Espírito Santo', abbr:'ES', country: country},
	{name:'Río de Janeiro', abbr:'RJ', country: country},
	{name:'Alagoas', abbr:'AL', country: country},
	{name:'Sergipe', abbr:'SE', country: country},
	{name:'Distrito Federal', abbr:'DF', country: country},
])
