country = Spree::Country.find_or_create_by_name(name: "Mexico", iso3: "MEX", iso: "MX", iso_name: "MEXICO", numcode: "484", states_required: true)

Spree::State.create!([
  {name:'Aguascalientes', abbr:'Ags', country:  country },
  {name:'Baja California', abbr:'BC', country:  country },
  {name:'Baja California Sur', abbr:'BCS', country:  country },
  {name:'Campeche', abbr:'Camp', country:  country },
  {name:'Coahuila de Zaragoza', abbr:'Chis', country:  country },
  {name:'Colima', abbr:'Chih', country:  country },
  {name:'Chiapas', abbr:'Coah', country:  country },
  {name:'Chihuahua', abbr:'Col', country:  country },
  {name:'Distrito Federal', abbr:'DF', country:  country },
  {name:'Durango', abbr:'Dgo', country:  country },
  {name:'Guanajuato', abbr:'Gto', country:  country },
  {name:'Guerrero', abbr:'Gro', country:  country },
  {name:'Hidalgo', abbr:'Hgo', country:  country },
  {name:'Jalisco', abbr:'Jal', country:  country },
  {name:'México', abbr:'Méx', country:  country },
  {name:'Michoacán de Ocampo', abbr:'Mich', country:  country },
  {name:'Morelos', abbr:'Mor', country:  country },
  {name:'Nayarit', abbr:'Nay', country:  country },
  {name:'Nuevo León', abbr:'NL', country:  country },
  {name:'Oaxaca', abbr:'Oax', country:  country },
  {name:'Puebla', abbr:'Pue', country:  country },
  {name:'Querétaro', abbr:'Qro', country:  country },
  {name:'Quintana Roo', abbr:'QR', country:  country },
  {name:'San Luis Potosí', abbr:'SLP', country:  country },
  {name:'Sinaloa', abbr:'Sin', country:  country },
  {name:'Sonora', abbr:'Son', country:  country },
  {name:'Tabasco', abbr:'Tab', country:  country },
  {name:'Tamaulipas', abbr:'Tamps', country:  country },
  {name:'Tlaxcala', abbr:'Tlax', country:  country },
  {name:'Veracruz de Ignacio de la Llave', abbr:'Ver.', country:  country },
  {name:'Yucatán', abbr:'Yuc', country:  country },
  {name:'Zacatecas', abbr:'Zac', country:  country },
])
